import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Header from "./componentes/Header/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // ✨ SOLUCIÓN DE HIDRATACIÓN 1: Añadir al <html> para silenciar errores de extensiones ✨
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        // ✨ SOLUCIÓN DE HIDRATACIÓN 2: También al <body> (por si acaso) ✨
        suppressHydrationWarning={true} 
      >
        <Header />
        
        {/* ✨ SOLUCIÓN DE ESPACIO: Aplicar padding condicional para móviles ✨ */}
        <div className="pt-8 pb-5 sm:pt-0 sm:pb-0">
          {children}
        </div>
      </body>
    </html>
  );
}