import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "maplibre-gl/dist/maplibre-gl.css";
import { NotificationProvider } from '@/context/NotificationContext';

// 🟢 Importamos la campanita global
import NotificationBell from "@/components/NotificationBell";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="es" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="bg-blue-50 text-gray-900 antialiased min-h-screen">
        <NotificationProvider>
          {/* 🟣 Header global con campanita */}
          <header className="flex items-center justify-between px-6 py-3 bg-white border-b shadow-sm">
            <h1 className="text-lg font-semibold text-gray-800">FixerApp</h1>

            {/* 🔔 Campanita de notificaciones */}
            <NotificationBell />
          </header>

          {/* Contenido dinámico de cada página */}
          <main className="p-4">{children}</main>
        </NotificationProvider>
      </body>
    </html>
  );
}
